//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEC.WS_Agregar_Bec {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="WS_Agregar_Bec.Agregar")]
    public interface Agregar {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/InsertarMultimediaRequest", ReplyAction="http://ws/Agregar/InsertarMultimediaResponse")]
        BEC.WS_Agregar_Bec.InsertarMultimediaResponse InsertarMultimedia(BEC.WS_Agregar_Bec.InsertarMultimediaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/InsertarMultimediaRequest", ReplyAction="http://ws/Agregar/InsertarMultimediaResponse")]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.InsertarMultimediaResponse> InsertarMultimediaAsync(BEC.WS_Agregar_Bec.InsertarMultimediaRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertaPrestamoMultimediaRequest", ReplyAction="http://ws/Agregar/insertaPrestamoMultimediaResponse")]
        BEC.WS_Agregar_Bec.insertaPrestamoMultimediaResponse insertaPrestamoMultimedia(BEC.WS_Agregar_Bec.insertaPrestamoMultimediaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertaPrestamoMultimediaRequest", ReplyAction="http://ws/Agregar/insertaPrestamoMultimediaResponse")]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertaPrestamoMultimediaResponse> insertaPrestamoMultimediaAsync(BEC.WS_Agregar_Bec.insertaPrestamoMultimediaRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarUsuario2Request", ReplyAction="http://ws/Agregar/insertarUsuario2Response")]
        BEC.WS_Agregar_Bec.insertarUsuario2Response insertarUsuario2(BEC.WS_Agregar_Bec.insertarUsuario2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarUsuario2Request", ReplyAction="http://ws/Agregar/insertarUsuario2Response")]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertarUsuario2Response> insertarUsuario2Async(BEC.WS_Agregar_Bec.insertarUsuario2Request request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://ws/)
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/InsertarStockRequest", ReplyAction="http://ws/Agregar/InsertarStockResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BEC.WS_Agregar_Bec.InsertarStockResponse InsertarStock(BEC.WS_Agregar_Bec.InsertarStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/InsertarStockRequest", ReplyAction="http://ws/Agregar/InsertarStockResponse")]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.InsertarStockResponse> InsertarStockAsync(BEC.WS_Agregar_Bec.InsertarStockRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarUsuario3Request", ReplyAction="http://ws/Agregar/insertarUsuario3Response")]
        BEC.WS_Agregar_Bec.insertarUsuario3Response insertarUsuario3(BEC.WS_Agregar_Bec.insertarUsuario3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarUsuario3Request", ReplyAction="http://ws/Agregar/insertarUsuario3Response")]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertarUsuario3Response> insertarUsuario3Async(BEC.WS_Agregar_Bec.insertarUsuario3Request request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarRolRequest", ReplyAction="http://ws/Agregar/insertarRolResponse")]
        BEC.WS_Agregar_Bec.insertarRolResponse insertarRol(BEC.WS_Agregar_Bec.insertarRolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarRolRequest", ReplyAction="http://ws/Agregar/insertarRolResponse")]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertarRolResponse> insertarRolAsync(BEC.WS_Agregar_Bec.insertarRolRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarFichaRequest", ReplyAction="http://ws/Agregar/insertarFichaResponse")]
        BEC.WS_Agregar_Bec.insertarFichaResponse insertarFicha(BEC.WS_Agregar_Bec.insertarFichaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarFichaRequest", ReplyAction="http://ws/Agregar/insertarFichaResponse")]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertarFichaResponse> insertarFichaAsync(BEC.WS_Agregar_Bec.insertarFichaRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/InsertarEstanteRequest", ReplyAction="http://ws/Agregar/InsertarEstanteResponse")]
        BEC.WS_Agregar_Bec.InsertarEstanteResponse InsertarEstante(BEC.WS_Agregar_Bec.InsertarEstanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/InsertarEstanteRequest", ReplyAction="http://ws/Agregar/InsertarEstanteResponse")]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.InsertarEstanteResponse> InsertarEstanteAsync(BEC.WS_Agregar_Bec.InsertarEstanteRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/InsertarLibroRequest", ReplyAction="http://ws/Agregar/InsertarLibroResponse")]
        BEC.WS_Agregar_Bec.InsertarLibroResponse InsertarLibro(BEC.WS_Agregar_Bec.InsertarLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/InsertarLibroRequest", ReplyAction="http://ws/Agregar/InsertarLibroResponse")]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.InsertarLibroResponse> InsertarLibroAsync(BEC.WS_Agregar_Bec.InsertarLibroRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarUsuarioRequest", ReplyAction="http://ws/Agregar/insertarUsuarioResponse")]
        BEC.WS_Agregar_Bec.insertarUsuarioResponse insertarUsuario(BEC.WS_Agregar_Bec.insertarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarUsuarioRequest", ReplyAction="http://ws/Agregar/insertarUsuarioResponse")]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertarUsuarioResponse> insertarUsuarioAsync(BEC.WS_Agregar_Bec.insertarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertaPrestamoRequest", ReplyAction="http://ws/Agregar/insertaPrestamoResponse")]
        BEC.WS_Agregar_Bec.insertaPrestamoResponse insertaPrestamo(BEC.WS_Agregar_Bec.insertaPrestamoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertaPrestamoRequest", ReplyAction="http://ws/Agregar/insertaPrestamoResponse")]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertaPrestamoResponse> insertaPrestamoAsync(BEC.WS_Agregar_Bec.insertaPrestamoRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarMultaRequest", ReplyAction="http://ws/Agregar/insertarMultaResponse")]
        BEC.WS_Agregar_Bec.insertarMultaResponse insertarMulta(BEC.WS_Agregar_Bec.insertarMultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarMultaRequest", ReplyAction="http://ws/Agregar/insertarMultaResponse")]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertarMultaResponse> insertarMultaAsync(BEC.WS_Agregar_Bec.insertarMultaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarMultimediaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarMultimedia", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.InsertarMultimediaRequestBody Body;
        
        public InsertarMultimediaRequest() {
        }
        
        public InsertarMultimediaRequest(BEC.WS_Agregar_Bec.InsertarMultimediaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InsertarMultimediaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int arg5;
        
        public InsertarMultimediaRequestBody() {
        }
        
        public InsertarMultimediaRequestBody(string arg0, string arg1, string arg2, string arg3, string arg4, int arg5) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarMultimediaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarMultimediaResponse", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.InsertarMultimediaResponseBody Body;
        
        public InsertarMultimediaResponse() {
        }
        
        public InsertarMultimediaResponse(BEC.WS_Agregar_Bec.InsertarMultimediaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InsertarMultimediaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public InsertarMultimediaResponseBody() {
        }
        
        public InsertarMultimediaResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertaPrestamoMultimediaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertaPrestamoMultimedia", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.insertaPrestamoMultimediaRequestBody Body;
        
        public insertaPrestamoMultimediaRequest() {
        }
        
        public insertaPrestamoMultimediaRequest(BEC.WS_Agregar_Bec.insertaPrestamoMultimediaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertaPrestamoMultimediaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int arg5;
        
        public insertaPrestamoMultimediaRequestBody() {
        }
        
        public insertaPrestamoMultimediaRequestBody(string arg0, string arg1, string arg2, string arg3, int arg4, int arg5) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertaPrestamoMultimediaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertaPrestamoMultimediaResponse", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.insertaPrestamoMultimediaResponseBody Body;
        
        public insertaPrestamoMultimediaResponse() {
        }
        
        public insertaPrestamoMultimediaResponse(BEC.WS_Agregar_Bec.insertaPrestamoMultimediaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertaPrestamoMultimediaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public insertaPrestamoMultimediaResponseBody() {
        }
        
        public insertaPrestamoMultimediaResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarUsuario2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarUsuario2", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.insertarUsuario2RequestBody Body;
        
        public insertarUsuario2Request() {
        }
        
        public insertarUsuario2Request(BEC.WS_Agregar_Bec.insertarUsuario2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarUsuario2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int arg4;
        
        public insertarUsuario2RequestBody() {
        }
        
        public insertarUsuario2RequestBody(string arg0, string arg1, int arg2, int arg3, int arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarUsuario2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarUsuario2Response", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.insertarUsuario2ResponseBody Body;
        
        public insertarUsuario2Response() {
        }
        
        public insertarUsuario2Response(BEC.WS_Agregar_Bec.insertarUsuario2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarUsuario2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public insertarUsuario2ResponseBody() {
        }
        
        public insertarUsuario2ResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertarStock", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class InsertarStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int arg3;
        
        public InsertarStockRequest() {
        }
        
        public InsertarStockRequest(int arg0, int arg1, int arg2, int arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertarStockResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class InsertarStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public InsertarStockResponse() {
        }
        
        public InsertarStockResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarUsuario3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarUsuario3", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.insertarUsuario3RequestBody Body;
        
        public insertarUsuario3Request() {
        }
        
        public insertarUsuario3Request(BEC.WS_Agregar_Bec.insertarUsuario3RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarUsuario3RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int arg4;
        
        public insertarUsuario3RequestBody() {
        }
        
        public insertarUsuario3RequestBody(string arg0, string arg1, int arg2, int arg3, int arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarUsuario3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarUsuario3Response", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.insertarUsuario3ResponseBody Body;
        
        public insertarUsuario3Response() {
        }
        
        public insertarUsuario3Response(BEC.WS_Agregar_Bec.insertarUsuario3ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarUsuario3ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public insertarUsuario3ResponseBody() {
        }
        
        public insertarUsuario3ResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarRolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarRol", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.insertarRolRequestBody Body;
        
        public insertarRolRequest() {
        }
        
        public insertarRolRequest(BEC.WS_Agregar_Bec.insertarRolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarRolRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public insertarRolRequestBody() {
        }
        
        public insertarRolRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarRolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarRolResponse", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.insertarRolResponseBody Body;
        
        public insertarRolResponse() {
        }
        
        public insertarRolResponse(BEC.WS_Agregar_Bec.insertarRolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarRolResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public insertarRolResponseBody() {
        }
        
        public insertarRolResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarFichaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarFicha", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.insertarFichaRequestBody Body;
        
        public insertarFichaRequest() {
        }
        
        public insertarFichaRequest(BEC.WS_Agregar_Bec.insertarFichaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarFichaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int arg5;
        
        public insertarFichaRequestBody() {
        }
        
        public insertarFichaRequestBody(string arg0, string arg1, string arg2, string arg3, string arg4, int arg5) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarFichaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarFichaResponse", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.insertarFichaResponseBody Body;
        
        public insertarFichaResponse() {
        }
        
        public insertarFichaResponse(BEC.WS_Agregar_Bec.insertarFichaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarFichaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public insertarFichaResponseBody() {
        }
        
        public insertarFichaResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarEstanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarEstante", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.InsertarEstanteRequestBody Body;
        
        public InsertarEstanteRequest() {
        }
        
        public InsertarEstanteRequest(BEC.WS_Agregar_Bec.InsertarEstanteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InsertarEstanteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public InsertarEstanteRequestBody() {
        }
        
        public InsertarEstanteRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarEstanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarEstanteResponse", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.InsertarEstanteResponseBody Body;
        
        public InsertarEstanteResponse() {
        }
        
        public InsertarEstanteResponse(BEC.WS_Agregar_Bec.InsertarEstanteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InsertarEstanteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public InsertarEstanteResponseBody() {
        }
        
        public InsertarEstanteResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarLibro", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.InsertarLibroRequestBody Body;
        
        public InsertarLibroRequest() {
        }
        
        public InsertarLibroRequest(BEC.WS_Agregar_Bec.InsertarLibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InsertarLibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string arg5;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int arg6;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int arg7;
        
        public InsertarLibroRequestBody() {
        }
        
        public InsertarLibroRequestBody(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, int arg6, int arg7) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarLibroResponse", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.InsertarLibroResponseBody Body;
        
        public InsertarLibroResponse() {
        }
        
        public InsertarLibroResponse(BEC.WS_Agregar_Bec.InsertarLibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InsertarLibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public InsertarLibroResponseBody() {
        }
        
        public InsertarLibroResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarUsuario", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.insertarUsuarioRequestBody Body;
        
        public insertarUsuarioRequest() {
        }
        
        public insertarUsuarioRequest(BEC.WS_Agregar_Bec.insertarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int arg4;
        
        public insertarUsuarioRequestBody() {
        }
        
        public insertarUsuarioRequestBody(string arg0, string arg1, int arg2, int arg3, int arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarUsuarioResponse", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.insertarUsuarioResponseBody Body;
        
        public insertarUsuarioResponse() {
        }
        
        public insertarUsuarioResponse(BEC.WS_Agregar_Bec.insertarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public insertarUsuarioResponseBody() {
        }
        
        public insertarUsuarioResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertaPrestamoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertaPrestamo", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.insertaPrestamoRequestBody Body;
        
        public insertaPrestamoRequest() {
        }
        
        public insertaPrestamoRequest(BEC.WS_Agregar_Bec.insertaPrestamoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertaPrestamoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int arg5;
        
        public insertaPrestamoRequestBody() {
        }
        
        public insertaPrestamoRequestBody(string arg0, string arg1, string arg2, string arg3, int arg4, int arg5) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertaPrestamoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertaPrestamoResponse", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.insertaPrestamoResponseBody Body;
        
        public insertaPrestamoResponse() {
        }
        
        public insertaPrestamoResponse(BEC.WS_Agregar_Bec.insertaPrestamoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertaPrestamoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public insertaPrestamoResponseBody() {
        }
        
        public insertaPrestamoResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarMultaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarMulta", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.insertarMultaRequestBody Body;
        
        public insertarMultaRequest() {
        }
        
        public insertarMultaRequest(BEC.WS_Agregar_Bec.insertarMultaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarMultaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int arg2;
        
        public insertarMultaRequestBody() {
        }
        
        public insertarMultaRequestBody(string arg0, int arg1, int arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarMultaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarMultaResponse", Namespace="http://ws/", Order=0)]
        public BEC.WS_Agregar_Bec.insertarMultaResponseBody Body;
        
        public insertarMultaResponse() {
        }
        
        public insertarMultaResponse(BEC.WS_Agregar_Bec.insertarMultaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarMultaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public insertarMultaResponseBody() {
        }
        
        public insertarMultaResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgregarChannel : BEC.WS_Agregar_Bec.Agregar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgregarClient : System.ServiceModel.ClientBase<BEC.WS_Agregar_Bec.Agregar>, BEC.WS_Agregar_Bec.Agregar {
        
        public AgregarClient() {
        }
        
        public AgregarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgregarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgregarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgregarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Agregar_Bec.InsertarMultimediaResponse BEC.WS_Agregar_Bec.Agregar.InsertarMultimedia(BEC.WS_Agregar_Bec.InsertarMultimediaRequest request) {
            return base.Channel.InsertarMultimedia(request);
        }
        
        public int InsertarMultimedia(string arg0, string arg1, string arg2, string arg3, string arg4, int arg5) {
            BEC.WS_Agregar_Bec.InsertarMultimediaRequest inValue = new BEC.WS_Agregar_Bec.InsertarMultimediaRequest();
            inValue.Body = new BEC.WS_Agregar_Bec.InsertarMultimediaRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            BEC.WS_Agregar_Bec.InsertarMultimediaResponse retVal = ((BEC.WS_Agregar_Bec.Agregar)(this)).InsertarMultimedia(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.InsertarMultimediaResponse> BEC.WS_Agregar_Bec.Agregar.InsertarMultimediaAsync(BEC.WS_Agregar_Bec.InsertarMultimediaRequest request) {
            return base.Channel.InsertarMultimediaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.InsertarMultimediaResponse> InsertarMultimediaAsync(string arg0, string arg1, string arg2, string arg3, string arg4, int arg5) {
            BEC.WS_Agregar_Bec.InsertarMultimediaRequest inValue = new BEC.WS_Agregar_Bec.InsertarMultimediaRequest();
            inValue.Body = new BEC.WS_Agregar_Bec.InsertarMultimediaRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            return ((BEC.WS_Agregar_Bec.Agregar)(this)).InsertarMultimediaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Agregar_Bec.insertaPrestamoMultimediaResponse BEC.WS_Agregar_Bec.Agregar.insertaPrestamoMultimedia(BEC.WS_Agregar_Bec.insertaPrestamoMultimediaRequest request) {
            return base.Channel.insertaPrestamoMultimedia(request);
        }
        
        public bool insertaPrestamoMultimedia(string arg0, string arg1, string arg2, string arg3, int arg4, int arg5) {
            BEC.WS_Agregar_Bec.insertaPrestamoMultimediaRequest inValue = new BEC.WS_Agregar_Bec.insertaPrestamoMultimediaRequest();
            inValue.Body = new BEC.WS_Agregar_Bec.insertaPrestamoMultimediaRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            BEC.WS_Agregar_Bec.insertaPrestamoMultimediaResponse retVal = ((BEC.WS_Agregar_Bec.Agregar)(this)).insertaPrestamoMultimedia(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertaPrestamoMultimediaResponse> BEC.WS_Agregar_Bec.Agregar.insertaPrestamoMultimediaAsync(BEC.WS_Agregar_Bec.insertaPrestamoMultimediaRequest request) {
            return base.Channel.insertaPrestamoMultimediaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertaPrestamoMultimediaResponse> insertaPrestamoMultimediaAsync(string arg0, string arg1, string arg2, string arg3, int arg4, int arg5) {
            BEC.WS_Agregar_Bec.insertaPrestamoMultimediaRequest inValue = new BEC.WS_Agregar_Bec.insertaPrestamoMultimediaRequest();
            inValue.Body = new BEC.WS_Agregar_Bec.insertaPrestamoMultimediaRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            return ((BEC.WS_Agregar_Bec.Agregar)(this)).insertaPrestamoMultimediaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Agregar_Bec.insertarUsuario2Response BEC.WS_Agregar_Bec.Agregar.insertarUsuario2(BEC.WS_Agregar_Bec.insertarUsuario2Request request) {
            return base.Channel.insertarUsuario2(request);
        }
        
        public bool insertarUsuario2(string arg0, string arg1, int arg2, int arg3, int arg4) {
            BEC.WS_Agregar_Bec.insertarUsuario2Request inValue = new BEC.WS_Agregar_Bec.insertarUsuario2Request();
            inValue.Body = new BEC.WS_Agregar_Bec.insertarUsuario2RequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            BEC.WS_Agregar_Bec.insertarUsuario2Response retVal = ((BEC.WS_Agregar_Bec.Agregar)(this)).insertarUsuario2(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertarUsuario2Response> BEC.WS_Agregar_Bec.Agregar.insertarUsuario2Async(BEC.WS_Agregar_Bec.insertarUsuario2Request request) {
            return base.Channel.insertarUsuario2Async(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertarUsuario2Response> insertarUsuario2Async(string arg0, string arg1, int arg2, int arg3, int arg4) {
            BEC.WS_Agregar_Bec.insertarUsuario2Request inValue = new BEC.WS_Agregar_Bec.insertarUsuario2Request();
            inValue.Body = new BEC.WS_Agregar_Bec.insertarUsuario2RequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            return ((BEC.WS_Agregar_Bec.Agregar)(this)).insertarUsuario2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Agregar_Bec.InsertarStockResponse BEC.WS_Agregar_Bec.Agregar.InsertarStock(BEC.WS_Agregar_Bec.InsertarStockRequest request) {
            return base.Channel.InsertarStock(request);
        }
        
        public int InsertarStock(int arg0, int arg1, int arg2, int arg3) {
            BEC.WS_Agregar_Bec.InsertarStockRequest inValue = new BEC.WS_Agregar_Bec.InsertarStockRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            BEC.WS_Agregar_Bec.InsertarStockResponse retVal = ((BEC.WS_Agregar_Bec.Agregar)(this)).InsertarStock(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.InsertarStockResponse> BEC.WS_Agregar_Bec.Agregar.InsertarStockAsync(BEC.WS_Agregar_Bec.InsertarStockRequest request) {
            return base.Channel.InsertarStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.InsertarStockResponse> InsertarStockAsync(int arg0, int arg1, int arg2, int arg3) {
            BEC.WS_Agregar_Bec.InsertarStockRequest inValue = new BEC.WS_Agregar_Bec.InsertarStockRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((BEC.WS_Agregar_Bec.Agregar)(this)).InsertarStockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Agregar_Bec.insertarUsuario3Response BEC.WS_Agregar_Bec.Agregar.insertarUsuario3(BEC.WS_Agregar_Bec.insertarUsuario3Request request) {
            return base.Channel.insertarUsuario3(request);
        }
        
        public bool insertarUsuario3(string arg0, string arg1, int arg2, int arg3, int arg4) {
            BEC.WS_Agregar_Bec.insertarUsuario3Request inValue = new BEC.WS_Agregar_Bec.insertarUsuario3Request();
            inValue.Body = new BEC.WS_Agregar_Bec.insertarUsuario3RequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            BEC.WS_Agregar_Bec.insertarUsuario3Response retVal = ((BEC.WS_Agregar_Bec.Agregar)(this)).insertarUsuario3(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertarUsuario3Response> BEC.WS_Agregar_Bec.Agregar.insertarUsuario3Async(BEC.WS_Agregar_Bec.insertarUsuario3Request request) {
            return base.Channel.insertarUsuario3Async(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertarUsuario3Response> insertarUsuario3Async(string arg0, string arg1, int arg2, int arg3, int arg4) {
            BEC.WS_Agregar_Bec.insertarUsuario3Request inValue = new BEC.WS_Agregar_Bec.insertarUsuario3Request();
            inValue.Body = new BEC.WS_Agregar_Bec.insertarUsuario3RequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            return ((BEC.WS_Agregar_Bec.Agregar)(this)).insertarUsuario3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Agregar_Bec.insertarRolResponse BEC.WS_Agregar_Bec.Agregar.insertarRol(BEC.WS_Agregar_Bec.insertarRolRequest request) {
            return base.Channel.insertarRol(request);
        }
        
        public bool insertarRol(string arg0) {
            BEC.WS_Agregar_Bec.insertarRolRequest inValue = new BEC.WS_Agregar_Bec.insertarRolRequest();
            inValue.Body = new BEC.WS_Agregar_Bec.insertarRolRequestBody();
            inValue.Body.arg0 = arg0;
            BEC.WS_Agregar_Bec.insertarRolResponse retVal = ((BEC.WS_Agregar_Bec.Agregar)(this)).insertarRol(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertarRolResponse> BEC.WS_Agregar_Bec.Agregar.insertarRolAsync(BEC.WS_Agregar_Bec.insertarRolRequest request) {
            return base.Channel.insertarRolAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertarRolResponse> insertarRolAsync(string arg0) {
            BEC.WS_Agregar_Bec.insertarRolRequest inValue = new BEC.WS_Agregar_Bec.insertarRolRequest();
            inValue.Body = new BEC.WS_Agregar_Bec.insertarRolRequestBody();
            inValue.Body.arg0 = arg0;
            return ((BEC.WS_Agregar_Bec.Agregar)(this)).insertarRolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Agregar_Bec.insertarFichaResponse BEC.WS_Agregar_Bec.Agregar.insertarFicha(BEC.WS_Agregar_Bec.insertarFichaRequest request) {
            return base.Channel.insertarFicha(request);
        }
        
        public int insertarFicha(string arg0, string arg1, string arg2, string arg3, string arg4, int arg5) {
            BEC.WS_Agregar_Bec.insertarFichaRequest inValue = new BEC.WS_Agregar_Bec.insertarFichaRequest();
            inValue.Body = new BEC.WS_Agregar_Bec.insertarFichaRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            BEC.WS_Agregar_Bec.insertarFichaResponse retVal = ((BEC.WS_Agregar_Bec.Agregar)(this)).insertarFicha(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertarFichaResponse> BEC.WS_Agregar_Bec.Agregar.insertarFichaAsync(BEC.WS_Agregar_Bec.insertarFichaRequest request) {
            return base.Channel.insertarFichaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertarFichaResponse> insertarFichaAsync(string arg0, string arg1, string arg2, string arg3, string arg4, int arg5) {
            BEC.WS_Agregar_Bec.insertarFichaRequest inValue = new BEC.WS_Agregar_Bec.insertarFichaRequest();
            inValue.Body = new BEC.WS_Agregar_Bec.insertarFichaRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            return ((BEC.WS_Agregar_Bec.Agregar)(this)).insertarFichaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Agregar_Bec.InsertarEstanteResponse BEC.WS_Agregar_Bec.Agregar.InsertarEstante(BEC.WS_Agregar_Bec.InsertarEstanteRequest request) {
            return base.Channel.InsertarEstante(request);
        }
        
        public int InsertarEstante(string arg0, string arg1) {
            BEC.WS_Agregar_Bec.InsertarEstanteRequest inValue = new BEC.WS_Agregar_Bec.InsertarEstanteRequest();
            inValue.Body = new BEC.WS_Agregar_Bec.InsertarEstanteRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            BEC.WS_Agregar_Bec.InsertarEstanteResponse retVal = ((BEC.WS_Agregar_Bec.Agregar)(this)).InsertarEstante(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.InsertarEstanteResponse> BEC.WS_Agregar_Bec.Agregar.InsertarEstanteAsync(BEC.WS_Agregar_Bec.InsertarEstanteRequest request) {
            return base.Channel.InsertarEstanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.InsertarEstanteResponse> InsertarEstanteAsync(string arg0, string arg1) {
            BEC.WS_Agregar_Bec.InsertarEstanteRequest inValue = new BEC.WS_Agregar_Bec.InsertarEstanteRequest();
            inValue.Body = new BEC.WS_Agregar_Bec.InsertarEstanteRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((BEC.WS_Agregar_Bec.Agregar)(this)).InsertarEstanteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Agregar_Bec.InsertarLibroResponse BEC.WS_Agregar_Bec.Agregar.InsertarLibro(BEC.WS_Agregar_Bec.InsertarLibroRequest request) {
            return base.Channel.InsertarLibro(request);
        }
        
        public int InsertarLibro(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, int arg6, int arg7) {
            BEC.WS_Agregar_Bec.InsertarLibroRequest inValue = new BEC.WS_Agregar_Bec.InsertarLibroRequest();
            inValue.Body = new BEC.WS_Agregar_Bec.InsertarLibroRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            inValue.Body.arg7 = arg7;
            BEC.WS_Agregar_Bec.InsertarLibroResponse retVal = ((BEC.WS_Agregar_Bec.Agregar)(this)).InsertarLibro(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.InsertarLibroResponse> BEC.WS_Agregar_Bec.Agregar.InsertarLibroAsync(BEC.WS_Agregar_Bec.InsertarLibroRequest request) {
            return base.Channel.InsertarLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.InsertarLibroResponse> InsertarLibroAsync(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, int arg6, int arg7) {
            BEC.WS_Agregar_Bec.InsertarLibroRequest inValue = new BEC.WS_Agregar_Bec.InsertarLibroRequest();
            inValue.Body = new BEC.WS_Agregar_Bec.InsertarLibroRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            inValue.Body.arg7 = arg7;
            return ((BEC.WS_Agregar_Bec.Agregar)(this)).InsertarLibroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Agregar_Bec.insertarUsuarioResponse BEC.WS_Agregar_Bec.Agregar.insertarUsuario(BEC.WS_Agregar_Bec.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuario(request);
        }
        
        public bool insertarUsuario(string arg0, string arg1, int arg2, int arg3, int arg4) {
            BEC.WS_Agregar_Bec.insertarUsuarioRequest inValue = new BEC.WS_Agregar_Bec.insertarUsuarioRequest();
            inValue.Body = new BEC.WS_Agregar_Bec.insertarUsuarioRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            BEC.WS_Agregar_Bec.insertarUsuarioResponse retVal = ((BEC.WS_Agregar_Bec.Agregar)(this)).insertarUsuario(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertarUsuarioResponse> BEC.WS_Agregar_Bec.Agregar.insertarUsuarioAsync(BEC.WS_Agregar_Bec.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertarUsuarioResponse> insertarUsuarioAsync(string arg0, string arg1, int arg2, int arg3, int arg4) {
            BEC.WS_Agregar_Bec.insertarUsuarioRequest inValue = new BEC.WS_Agregar_Bec.insertarUsuarioRequest();
            inValue.Body = new BEC.WS_Agregar_Bec.insertarUsuarioRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            return ((BEC.WS_Agregar_Bec.Agregar)(this)).insertarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Agregar_Bec.insertaPrestamoResponse BEC.WS_Agregar_Bec.Agregar.insertaPrestamo(BEC.WS_Agregar_Bec.insertaPrestamoRequest request) {
            return base.Channel.insertaPrestamo(request);
        }
        
        public bool insertaPrestamo(string arg0, string arg1, string arg2, string arg3, int arg4, int arg5) {
            BEC.WS_Agregar_Bec.insertaPrestamoRequest inValue = new BEC.WS_Agregar_Bec.insertaPrestamoRequest();
            inValue.Body = new BEC.WS_Agregar_Bec.insertaPrestamoRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            BEC.WS_Agregar_Bec.insertaPrestamoResponse retVal = ((BEC.WS_Agregar_Bec.Agregar)(this)).insertaPrestamo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertaPrestamoResponse> BEC.WS_Agregar_Bec.Agregar.insertaPrestamoAsync(BEC.WS_Agregar_Bec.insertaPrestamoRequest request) {
            return base.Channel.insertaPrestamoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertaPrestamoResponse> insertaPrestamoAsync(string arg0, string arg1, string arg2, string arg3, int arg4, int arg5) {
            BEC.WS_Agregar_Bec.insertaPrestamoRequest inValue = new BEC.WS_Agregar_Bec.insertaPrestamoRequest();
            inValue.Body = new BEC.WS_Agregar_Bec.insertaPrestamoRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            return ((BEC.WS_Agregar_Bec.Agregar)(this)).insertaPrestamoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Agregar_Bec.insertarMultaResponse BEC.WS_Agregar_Bec.Agregar.insertarMulta(BEC.WS_Agregar_Bec.insertarMultaRequest request) {
            return base.Channel.insertarMulta(request);
        }
        
        public int insertarMulta(string arg0, int arg1, int arg2) {
            BEC.WS_Agregar_Bec.insertarMultaRequest inValue = new BEC.WS_Agregar_Bec.insertarMultaRequest();
            inValue.Body = new BEC.WS_Agregar_Bec.insertarMultaRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            BEC.WS_Agregar_Bec.insertarMultaResponse retVal = ((BEC.WS_Agregar_Bec.Agregar)(this)).insertarMulta(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertarMultaResponse> BEC.WS_Agregar_Bec.Agregar.insertarMultaAsync(BEC.WS_Agregar_Bec.insertarMultaRequest request) {
            return base.Channel.insertarMultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Agregar_Bec.insertarMultaResponse> insertarMultaAsync(string arg0, int arg1, int arg2) {
            BEC.WS_Agregar_Bec.insertarMultaRequest inValue = new BEC.WS_Agregar_Bec.insertarMultaRequest();
            inValue.Body = new BEC.WS_Agregar_Bec.insertarMultaRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            return ((BEC.WS_Agregar_Bec.Agregar)(this)).insertarMultaAsync(inValue);
        }
    }
}
