//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFC_Service_Bec.WS_Login_Bec {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="WS_Login_Bec.Login")]
    public interface Login {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://ws/)
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Login/iniciarSesionRequest", ReplyAction="http://ws/Login/iniciarSesionResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WFC_Service_Bec.WS_Login_Bec.iniciarSesionResponse iniciarSesion(WFC_Service_Bec.WS_Login_Bec.iniciarSesionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Login/iniciarSesionRequest", ReplyAction="http://ws/Login/iniciarSesionResponse")]
        System.Threading.Tasks.Task<WFC_Service_Bec.WS_Login_Bec.iniciarSesionResponse> iniciarSesionAsync(WFC_Service_Bec.WS_Login_Bec.iniciarSesionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iniciarSesion", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class iniciarSesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        public iniciarSesionRequest() {
        }
        
        public iniciarSesionRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iniciarSesionResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class iniciarSesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public iniciarSesionResponse() {
        }
        
        public iniciarSesionResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginChannel : WFC_Service_Bec.WS_Login_Bec.Login, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginClient : System.ServiceModel.ClientBase<WFC_Service_Bec.WS_Login_Bec.Login>, WFC_Service_Bec.WS_Login_Bec.Login {
        
        public LoginClient() {
        }
        
        public LoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WFC_Service_Bec.WS_Login_Bec.iniciarSesionResponse WFC_Service_Bec.WS_Login_Bec.Login.iniciarSesion(WFC_Service_Bec.WS_Login_Bec.iniciarSesionRequest request) {
            return base.Channel.iniciarSesion(request);
        }
        
        public bool iniciarSesion(int arg0) {
            WFC_Service_Bec.WS_Login_Bec.iniciarSesionRequest inValue = new WFC_Service_Bec.WS_Login_Bec.iniciarSesionRequest();
            inValue.arg0 = arg0;
            WFC_Service_Bec.WS_Login_Bec.iniciarSesionResponse retVal = ((WFC_Service_Bec.WS_Login_Bec.Login)(this)).iniciarSesion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WFC_Service_Bec.WS_Login_Bec.iniciarSesionResponse> WFC_Service_Bec.WS_Login_Bec.Login.iniciarSesionAsync(WFC_Service_Bec.WS_Login_Bec.iniciarSesionRequest request) {
            return base.Channel.iniciarSesionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WFC_Service_Bec.WS_Login_Bec.iniciarSesionResponse> iniciarSesionAsync(int arg0) {
            WFC_Service_Bec.WS_Login_Bec.iniciarSesionRequest inValue = new WFC_Service_Bec.WS_Login_Bec.iniciarSesionRequest();
            inValue.arg0 = arg0;
            return ((WFC_Service_Bec.WS_Login_Bec.Login)(this)).iniciarSesionAsync(inValue);
        }
    }
}
