//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEC.WS_Actualizar_Bec {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="WS_Actualizar_Bec.Actualizar")]
    public interface Actualizar {
        
        // CODEGEN: Generating message contract since element name arg1 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/ActualizarFichaRequest", ReplyAction="http://ws/Actualizar/ActualizarFichaResponse")]
        BEC.WS_Actualizar_Bec.ActualizarFichaResponse ActualizarFicha(BEC.WS_Actualizar_Bec.ActualizarFichaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/ActualizarFichaRequest", ReplyAction="http://ws/Actualizar/ActualizarFichaResponse")]
        System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.ActualizarFichaResponse> ActualizarFichaAsync(BEC.WS_Actualizar_Bec.ActualizarFichaRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://ws/)
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/ActualizarStockRequest", ReplyAction="http://ws/Actualizar/ActualizarStockResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BEC.WS_Actualizar_Bec.ActualizarStockResponse ActualizarStock(BEC.WS_Actualizar_Bec.ActualizarStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/ActualizarStockRequest", ReplyAction="http://ws/Actualizar/ActualizarStockResponse")]
        System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.ActualizarStockResponse> ActualizarStockAsync(BEC.WS_Actualizar_Bec.ActualizarStockRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/actualizarRolRequest", ReplyAction="http://ws/Actualizar/actualizarRolResponse")]
        BEC.WS_Actualizar_Bec.actualizarRolResponse actualizarRol(BEC.WS_Actualizar_Bec.actualizarRolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/actualizarRolRequest", ReplyAction="http://ws/Actualizar/actualizarRolResponse")]
        System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.actualizarRolResponse> actualizarRolAsync(BEC.WS_Actualizar_Bec.actualizarRolRequest request);
        
        // CODEGEN: Generating message contract since element name arg1 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/actualizarPrestamoMultimediaSinMoraRequest", ReplyAction="http://ws/Actualizar/actualizarPrestamoMultimediaSinMoraResponse")]
        BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraResponse actualizarPrestamoMultimediaSinMora(BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/actualizarPrestamoMultimediaSinMoraRequest", ReplyAction="http://ws/Actualizar/actualizarPrestamoMultimediaSinMoraResponse")]
        System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraResponse> actualizarPrestamoMultimediaSinMoraAsync(BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraRequest request);
        
        // CODEGEN: Generating message contract since element name arg1 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/actualizarPrestamoLibroSinMoraRequest", ReplyAction="http://ws/Actualizar/actualizarPrestamoLibroSinMoraResponse")]
        BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraResponse actualizarPrestamoLibroSinMora(BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/actualizarPrestamoLibroSinMoraRequest", ReplyAction="http://ws/Actualizar/actualizarPrestamoLibroSinMoraResponse")]
        System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraResponse> actualizarPrestamoLibroSinMoraAsync(BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraRequest request);
        
        // CODEGEN: Generating message contract since element name arg1 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/actualizarPrestamoLibroRequest", ReplyAction="http://ws/Actualizar/actualizarPrestamoLibroResponse")]
        BEC.WS_Actualizar_Bec.actualizarPrestamoLibroResponse actualizarPrestamoLibro(BEC.WS_Actualizar_Bec.actualizarPrestamoLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/actualizarPrestamoLibroRequest", ReplyAction="http://ws/Actualizar/actualizarPrestamoLibroResponse")]
        System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.actualizarPrestamoLibroResponse> actualizarPrestamoLibroAsync(BEC.WS_Actualizar_Bec.actualizarPrestamoLibroRequest request);
        
        // CODEGEN: Generating message contract since element name arg1 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/actualizarPrestamoMultimediaRequest", ReplyAction="http://ws/Actualizar/actualizarPrestamoMultimediaResponse")]
        BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaResponse actualizarPrestamoMultimedia(BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/actualizarPrestamoMultimediaRequest", ReplyAction="http://ws/Actualizar/actualizarPrestamoMultimediaResponse")]
        System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaResponse> actualizarPrestamoMultimediaAsync(BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaRequest request);
        
        // CODEGEN: Generating message contract since element name arg1 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/actualizarUsuarioRequest", ReplyAction="http://ws/Actualizar/actualizarUsuarioResponse")]
        BEC.WS_Actualizar_Bec.actualizarUsuarioResponse actualizarUsuario(BEC.WS_Actualizar_Bec.actualizarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/actualizarUsuarioRequest", ReplyAction="http://ws/Actualizar/actualizarUsuarioResponse")]
        System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.actualizarUsuarioResponse> actualizarUsuarioAsync(BEC.WS_Actualizar_Bec.actualizarUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarFichaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarFicha", Namespace="http://ws/", Order=0)]
        public BEC.WS_Actualizar_Bec.ActualizarFichaRequestBody Body;
        
        public ActualizarFichaRequest() {
        }
        
        public ActualizarFichaRequest(BEC.WS_Actualizar_Bec.ActualizarFichaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ActualizarFichaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string arg5;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int arg6;
        
        public ActualizarFichaRequestBody() {
        }
        
        public ActualizarFichaRequestBody(int arg0, string arg1, string arg2, string arg3, string arg4, string arg5, int arg6) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarFichaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarFichaResponse", Namespace="http://ws/", Order=0)]
        public BEC.WS_Actualizar_Bec.ActualizarFichaResponseBody Body;
        
        public ActualizarFichaResponse() {
        }
        
        public ActualizarFichaResponse(BEC.WS_Actualizar_Bec.ActualizarFichaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ActualizarFichaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public ActualizarFichaResponseBody() {
        }
        
        public ActualizarFichaResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarStock", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ActualizarStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int arg4;
        
        public ActualizarStockRequest() {
        }
        
        public ActualizarStockRequest(int arg0, int arg1, int arg2, int arg3, int arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarStockResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ActualizarStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public ActualizarStockResponse() {
        }
        
        public ActualizarStockResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarRolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarRol", Namespace="http://ws/", Order=0)]
        public BEC.WS_Actualizar_Bec.actualizarRolRequestBody Body;
        
        public actualizarRolRequest() {
        }
        
        public actualizarRolRequest(BEC.WS_Actualizar_Bec.actualizarRolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarRolRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public actualizarRolRequestBody() {
        }
        
        public actualizarRolRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarRolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarRolResponse", Namespace="http://ws/", Order=0)]
        public BEC.WS_Actualizar_Bec.actualizarRolResponseBody Body;
        
        public actualizarRolResponse() {
        }
        
        public actualizarRolResponse(BEC.WS_Actualizar_Bec.actualizarRolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarRolResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public actualizarRolResponseBody() {
        }
        
        public actualizarRolResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarPrestamoMultimediaSinMoraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarPrestamoMultimediaSinMora", Namespace="http://ws/", Order=0)]
        public BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraRequestBody Body;
        
        public actualizarPrestamoMultimediaSinMoraRequest() {
        }
        
        public actualizarPrestamoMultimediaSinMoraRequest(BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarPrestamoMultimediaSinMoraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int arg5;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int arg6;
        
        public actualizarPrestamoMultimediaSinMoraRequestBody() {
        }
        
        public actualizarPrestamoMultimediaSinMoraRequestBody(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, int arg6) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarPrestamoMultimediaSinMoraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarPrestamoMultimediaSinMoraResponse", Namespace="http://ws/", Order=0)]
        public BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraResponseBody Body;
        
        public actualizarPrestamoMultimediaSinMoraResponse() {
        }
        
        public actualizarPrestamoMultimediaSinMoraResponse(BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarPrestamoMultimediaSinMoraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public actualizarPrestamoMultimediaSinMoraResponseBody() {
        }
        
        public actualizarPrestamoMultimediaSinMoraResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarPrestamoLibroSinMoraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarPrestamoLibroSinMora", Namespace="http://ws/", Order=0)]
        public BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraRequestBody Body;
        
        public actualizarPrestamoLibroSinMoraRequest() {
        }
        
        public actualizarPrestamoLibroSinMoraRequest(BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarPrestamoLibroSinMoraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int arg5;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int arg6;
        
        public actualizarPrestamoLibroSinMoraRequestBody() {
        }
        
        public actualizarPrestamoLibroSinMoraRequestBody(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, int arg6) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarPrestamoLibroSinMoraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarPrestamoLibroSinMoraResponse", Namespace="http://ws/", Order=0)]
        public BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraResponseBody Body;
        
        public actualizarPrestamoLibroSinMoraResponse() {
        }
        
        public actualizarPrestamoLibroSinMoraResponse(BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarPrestamoLibroSinMoraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public actualizarPrestamoLibroSinMoraResponseBody() {
        }
        
        public actualizarPrestamoLibroSinMoraResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarPrestamoLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarPrestamoLibro", Namespace="http://ws/", Order=0)]
        public BEC.WS_Actualizar_Bec.actualizarPrestamoLibroRequestBody Body;
        
        public actualizarPrestamoLibroRequest() {
        }
        
        public actualizarPrestamoLibroRequest(BEC.WS_Actualizar_Bec.actualizarPrestamoLibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarPrestamoLibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int arg5;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int arg6;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int arg7;
        
        public actualizarPrestamoLibroRequestBody() {
        }
        
        public actualizarPrestamoLibroRequestBody(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, int arg6, int arg7) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarPrestamoLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarPrestamoLibroResponse", Namespace="http://ws/", Order=0)]
        public BEC.WS_Actualizar_Bec.actualizarPrestamoLibroResponseBody Body;
        
        public actualizarPrestamoLibroResponse() {
        }
        
        public actualizarPrestamoLibroResponse(BEC.WS_Actualizar_Bec.actualizarPrestamoLibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarPrestamoLibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public actualizarPrestamoLibroResponseBody() {
        }
        
        public actualizarPrestamoLibroResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarPrestamoMultimediaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarPrestamoMultimedia", Namespace="http://ws/", Order=0)]
        public BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaRequestBody Body;
        
        public actualizarPrestamoMultimediaRequest() {
        }
        
        public actualizarPrestamoMultimediaRequest(BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarPrestamoMultimediaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int arg5;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int arg6;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int arg7;
        
        public actualizarPrestamoMultimediaRequestBody() {
        }
        
        public actualizarPrestamoMultimediaRequestBody(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, int arg6, int arg7) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarPrestamoMultimediaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarPrestamoMultimediaResponse", Namespace="http://ws/", Order=0)]
        public BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaResponseBody Body;
        
        public actualizarPrestamoMultimediaResponse() {
        }
        
        public actualizarPrestamoMultimediaResponse(BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarPrestamoMultimediaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public actualizarPrestamoMultimediaResponseBody() {
        }
        
        public actualizarPrestamoMultimediaResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarUsuario", Namespace="http://ws/", Order=0)]
        public BEC.WS_Actualizar_Bec.actualizarUsuarioRequestBody Body;
        
        public actualizarUsuarioRequest() {
        }
        
        public actualizarUsuarioRequest(BEC.WS_Actualizar_Bec.actualizarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int arg5;
        
        public actualizarUsuarioRequestBody() {
        }
        
        public actualizarUsuarioRequestBody(int arg0, string arg1, string arg2, int arg3, int arg4, int arg5) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarUsuarioResponse", Namespace="http://ws/", Order=0)]
        public BEC.WS_Actualizar_Bec.actualizarUsuarioResponseBody Body;
        
        public actualizarUsuarioResponse() {
        }
        
        public actualizarUsuarioResponse(BEC.WS_Actualizar_Bec.actualizarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public actualizarUsuarioResponseBody() {
        }
        
        public actualizarUsuarioResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ActualizarChannel : BEC.WS_Actualizar_Bec.Actualizar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActualizarClient : System.ServiceModel.ClientBase<BEC.WS_Actualizar_Bec.Actualizar>, BEC.WS_Actualizar_Bec.Actualizar {
        
        public ActualizarClient() {
        }
        
        public ActualizarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActualizarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActualizarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActualizarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Actualizar_Bec.ActualizarFichaResponse BEC.WS_Actualizar_Bec.Actualizar.ActualizarFicha(BEC.WS_Actualizar_Bec.ActualizarFichaRequest request) {
            return base.Channel.ActualizarFicha(request);
        }
        
        public bool ActualizarFicha(int arg0, string arg1, string arg2, string arg3, string arg4, string arg5, int arg6) {
            BEC.WS_Actualizar_Bec.ActualizarFichaRequest inValue = new BEC.WS_Actualizar_Bec.ActualizarFichaRequest();
            inValue.Body = new BEC.WS_Actualizar_Bec.ActualizarFichaRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            BEC.WS_Actualizar_Bec.ActualizarFichaResponse retVal = ((BEC.WS_Actualizar_Bec.Actualizar)(this)).ActualizarFicha(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.ActualizarFichaResponse> BEC.WS_Actualizar_Bec.Actualizar.ActualizarFichaAsync(BEC.WS_Actualizar_Bec.ActualizarFichaRequest request) {
            return base.Channel.ActualizarFichaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.ActualizarFichaResponse> ActualizarFichaAsync(int arg0, string arg1, string arg2, string arg3, string arg4, string arg5, int arg6) {
            BEC.WS_Actualizar_Bec.ActualizarFichaRequest inValue = new BEC.WS_Actualizar_Bec.ActualizarFichaRequest();
            inValue.Body = new BEC.WS_Actualizar_Bec.ActualizarFichaRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            return ((BEC.WS_Actualizar_Bec.Actualizar)(this)).ActualizarFichaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Actualizar_Bec.ActualizarStockResponse BEC.WS_Actualizar_Bec.Actualizar.ActualizarStock(BEC.WS_Actualizar_Bec.ActualizarStockRequest request) {
            return base.Channel.ActualizarStock(request);
        }
        
        public bool ActualizarStock(int arg0, int arg1, int arg2, int arg3, int arg4) {
            BEC.WS_Actualizar_Bec.ActualizarStockRequest inValue = new BEC.WS_Actualizar_Bec.ActualizarStockRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            BEC.WS_Actualizar_Bec.ActualizarStockResponse retVal = ((BEC.WS_Actualizar_Bec.Actualizar)(this)).ActualizarStock(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.ActualizarStockResponse> BEC.WS_Actualizar_Bec.Actualizar.ActualizarStockAsync(BEC.WS_Actualizar_Bec.ActualizarStockRequest request) {
            return base.Channel.ActualizarStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.ActualizarStockResponse> ActualizarStockAsync(int arg0, int arg1, int arg2, int arg3, int arg4) {
            BEC.WS_Actualizar_Bec.ActualizarStockRequest inValue = new BEC.WS_Actualizar_Bec.ActualizarStockRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            return ((BEC.WS_Actualizar_Bec.Actualizar)(this)).ActualizarStockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Actualizar_Bec.actualizarRolResponse BEC.WS_Actualizar_Bec.Actualizar.actualizarRol(BEC.WS_Actualizar_Bec.actualizarRolRequest request) {
            return base.Channel.actualizarRol(request);
        }
        
        public bool actualizarRol(string arg0) {
            BEC.WS_Actualizar_Bec.actualizarRolRequest inValue = new BEC.WS_Actualizar_Bec.actualizarRolRequest();
            inValue.Body = new BEC.WS_Actualizar_Bec.actualizarRolRequestBody();
            inValue.Body.arg0 = arg0;
            BEC.WS_Actualizar_Bec.actualizarRolResponse retVal = ((BEC.WS_Actualizar_Bec.Actualizar)(this)).actualizarRol(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.actualizarRolResponse> BEC.WS_Actualizar_Bec.Actualizar.actualizarRolAsync(BEC.WS_Actualizar_Bec.actualizarRolRequest request) {
            return base.Channel.actualizarRolAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.actualizarRolResponse> actualizarRolAsync(string arg0) {
            BEC.WS_Actualizar_Bec.actualizarRolRequest inValue = new BEC.WS_Actualizar_Bec.actualizarRolRequest();
            inValue.Body = new BEC.WS_Actualizar_Bec.actualizarRolRequestBody();
            inValue.Body.arg0 = arg0;
            return ((BEC.WS_Actualizar_Bec.Actualizar)(this)).actualizarRolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraResponse BEC.WS_Actualizar_Bec.Actualizar.actualizarPrestamoMultimediaSinMora(BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraRequest request) {
            return base.Channel.actualizarPrestamoMultimediaSinMora(request);
        }
        
        public bool actualizarPrestamoMultimediaSinMora(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, int arg6) {
            BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraRequest inValue = new BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraRequest();
            inValue.Body = new BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraResponse retVal = ((BEC.WS_Actualizar_Bec.Actualizar)(this)).actualizarPrestamoMultimediaSinMora(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraResponse> BEC.WS_Actualizar_Bec.Actualizar.actualizarPrestamoMultimediaSinMoraAsync(BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraRequest request) {
            return base.Channel.actualizarPrestamoMultimediaSinMoraAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraResponse> actualizarPrestamoMultimediaSinMoraAsync(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, int arg6) {
            BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraRequest inValue = new BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraRequest();
            inValue.Body = new BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaSinMoraRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            return ((BEC.WS_Actualizar_Bec.Actualizar)(this)).actualizarPrestamoMultimediaSinMoraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraResponse BEC.WS_Actualizar_Bec.Actualizar.actualizarPrestamoLibroSinMora(BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraRequest request) {
            return base.Channel.actualizarPrestamoLibroSinMora(request);
        }
        
        public bool actualizarPrestamoLibroSinMora(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, int arg6) {
            BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraRequest inValue = new BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraRequest();
            inValue.Body = new BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraResponse retVal = ((BEC.WS_Actualizar_Bec.Actualizar)(this)).actualizarPrestamoLibroSinMora(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraResponse> BEC.WS_Actualizar_Bec.Actualizar.actualizarPrestamoLibroSinMoraAsync(BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraRequest request) {
            return base.Channel.actualizarPrestamoLibroSinMoraAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraResponse> actualizarPrestamoLibroSinMoraAsync(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, int arg6) {
            BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraRequest inValue = new BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraRequest();
            inValue.Body = new BEC.WS_Actualizar_Bec.actualizarPrestamoLibroSinMoraRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            return ((BEC.WS_Actualizar_Bec.Actualizar)(this)).actualizarPrestamoLibroSinMoraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Actualizar_Bec.actualizarPrestamoLibroResponse BEC.WS_Actualizar_Bec.Actualizar.actualizarPrestamoLibro(BEC.WS_Actualizar_Bec.actualizarPrestamoLibroRequest request) {
            return base.Channel.actualizarPrestamoLibro(request);
        }
        
        public bool actualizarPrestamoLibro(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, int arg6, int arg7) {
            BEC.WS_Actualizar_Bec.actualizarPrestamoLibroRequest inValue = new BEC.WS_Actualizar_Bec.actualizarPrestamoLibroRequest();
            inValue.Body = new BEC.WS_Actualizar_Bec.actualizarPrestamoLibroRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            inValue.Body.arg7 = arg7;
            BEC.WS_Actualizar_Bec.actualizarPrestamoLibroResponse retVal = ((BEC.WS_Actualizar_Bec.Actualizar)(this)).actualizarPrestamoLibro(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.actualizarPrestamoLibroResponse> BEC.WS_Actualizar_Bec.Actualizar.actualizarPrestamoLibroAsync(BEC.WS_Actualizar_Bec.actualizarPrestamoLibroRequest request) {
            return base.Channel.actualizarPrestamoLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.actualizarPrestamoLibroResponse> actualizarPrestamoLibroAsync(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, int arg6, int arg7) {
            BEC.WS_Actualizar_Bec.actualizarPrestamoLibroRequest inValue = new BEC.WS_Actualizar_Bec.actualizarPrestamoLibroRequest();
            inValue.Body = new BEC.WS_Actualizar_Bec.actualizarPrestamoLibroRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            inValue.Body.arg7 = arg7;
            return ((BEC.WS_Actualizar_Bec.Actualizar)(this)).actualizarPrestamoLibroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaResponse BEC.WS_Actualizar_Bec.Actualizar.actualizarPrestamoMultimedia(BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaRequest request) {
            return base.Channel.actualizarPrestamoMultimedia(request);
        }
        
        public bool actualizarPrestamoMultimedia(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, int arg6, int arg7) {
            BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaRequest inValue = new BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaRequest();
            inValue.Body = new BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            inValue.Body.arg7 = arg7;
            BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaResponse retVal = ((BEC.WS_Actualizar_Bec.Actualizar)(this)).actualizarPrestamoMultimedia(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaResponse> BEC.WS_Actualizar_Bec.Actualizar.actualizarPrestamoMultimediaAsync(BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaRequest request) {
            return base.Channel.actualizarPrestamoMultimediaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaResponse> actualizarPrestamoMultimediaAsync(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, int arg6, int arg7) {
            BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaRequest inValue = new BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaRequest();
            inValue.Body = new BEC.WS_Actualizar_Bec.actualizarPrestamoMultimediaRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            inValue.Body.arg7 = arg7;
            return ((BEC.WS_Actualizar_Bec.Actualizar)(this)).actualizarPrestamoMultimediaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Actualizar_Bec.actualizarUsuarioResponse BEC.WS_Actualizar_Bec.Actualizar.actualizarUsuario(BEC.WS_Actualizar_Bec.actualizarUsuarioRequest request) {
            return base.Channel.actualizarUsuario(request);
        }
        
        public bool actualizarUsuario(int arg0, string arg1, string arg2, int arg3, int arg4, int arg5) {
            BEC.WS_Actualizar_Bec.actualizarUsuarioRequest inValue = new BEC.WS_Actualizar_Bec.actualizarUsuarioRequest();
            inValue.Body = new BEC.WS_Actualizar_Bec.actualizarUsuarioRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            BEC.WS_Actualizar_Bec.actualizarUsuarioResponse retVal = ((BEC.WS_Actualizar_Bec.Actualizar)(this)).actualizarUsuario(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.actualizarUsuarioResponse> BEC.WS_Actualizar_Bec.Actualizar.actualizarUsuarioAsync(BEC.WS_Actualizar_Bec.actualizarUsuarioRequest request) {
            return base.Channel.actualizarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Actualizar_Bec.actualizarUsuarioResponse> actualizarUsuarioAsync(int arg0, string arg1, string arg2, int arg3, int arg4, int arg5) {
            BEC.WS_Actualizar_Bec.actualizarUsuarioRequest inValue = new BEC.WS_Actualizar_Bec.actualizarUsuarioRequest();
            inValue.Body = new BEC.WS_Actualizar_Bec.actualizarUsuarioRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            return ((BEC.WS_Actualizar_Bec.Actualizar)(this)).actualizarUsuarioAsync(inValue);
        }
    }
}
