package cl.biblioteca.edm;
// Generated 28-oct-2017 22:26:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private Integer idLibro;
    
     private String isbn;
     private String codigo;
     private String nombre;
     private String autor;
     private String genero;
     private String fecha;
     private int popularidad;
     private int idstock;

    public Libro() {
    }

	
    public Libro(String isbn, String codigo, String nombre, String autor, String genero, String fecha, int popularidad, int stock) {
        
        this.isbn = isbn;
        this.codigo = codigo;
        this.nombre = nombre;
        this.autor = autor;
        this.genero = genero;
        this.fecha = fecha;
        this.popularidad = popularidad;
        this.idstock = stock;
    }

    public int getIdstock() {
        return idstock;
    }

    public void setIdstock(int idstock) {
        this.idstock = idstock;
    }
 
    public Integer getIdLibro() {
        return this.idLibro;
    }
    
    public void setIdLibro(Integer idLibro) {
        this.idLibro = idLibro;
    }
  
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public int getPopularidad() {
        return this.popularidad;
    }
    
    public void setPopularidad(int popularidad) {
        this.popularidad = popularidad;
    }


}


