package cl.biblioteca.edm;
// Generated 28-oct-2017 22:26:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Multa generated by hbm2java
 */
public class Multa  implements java.io.Serializable {


     private Integer idMulta;
     private String estado;
     private int tiempo;
     private int total;
     private Set<Prestamo> prestamos = new HashSet<Prestamo>(0);

    public Multa() {
    }

	
    public Multa(String estado, int tiempo, int total) {
        this.estado = estado;
        this.tiempo = tiempo;
        this.total = total;
    }
    public Multa(String estado, int tiempo, int total, Set<Prestamo> prestamos) {
       this.estado = estado;
       this.tiempo = tiempo;
       this.total = total;
       this.prestamos = prestamos;
    }
   
    public Integer getIdMulta() {
        return this.idMulta;
    }
    
    public void setIdMulta(Integer idMulta) {
        this.idMulta = idMulta;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public int getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(int tiempo) {
        this.tiempo = tiempo;
    }
    public int getTotal() {
        return this.total;
    }
    
    public void setTotal(int total) {
        this.total = total;
    }
    public Set<Prestamo> getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set<Prestamo> prestamos) {
        this.prestamos = prestamos;
    }




}


