package cl.biblioteca.edm;
// Generated 28-oct-2017 22:26:50 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private Integer idPrestamo;
     private Integer idLibro;
     private Integer idMulta;
     private Integer idMultimedia;
     private Integer idUsuario;
     private String tipo;
     private String estado;
     private String fechaPrestamo;
     private String fechaDevolucion;

    public Prestamo() {
    }

    public Prestamo(Integer libro, Integer multa, Integer multimedia, Integer usuario, String tipo, String estado, String fechaPrestamo, String fechaDevolucion) {
       this.idLibro = libro;
       this.idMulta = multa;
       this.idMultimedia = multimedia;
       this.idUsuario = usuario;
       this.tipo = tipo;
       this.estado = estado;
       this.fechaPrestamo = fechaPrestamo;
       this.fechaDevolucion = fechaDevolucion;
    }
   
    public Integer getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(Integer idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public Integer getIdLibro() {
        return this.idLibro;
    }
    
    public void setIdLibro(Integer idLibro) {
        this.idLibro = idLibro;
    }
    public Integer getIdMulta() {
        return this.idMulta;
    }
    
    public void setIdMulta(Integer idMulta) {
        this.idMulta = idMulta;
    }
    public Integer getIdMultimedia() {
        return this.idMultimedia;
    }
    
    public void setIdMultimedia(Integer idMultimedia) {
        this.idMultimedia = idMultimedia;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getFechaPrestamo() {
        return this.fechaPrestamo;
    }
    
    public void setFechaPrestamo(String fechaPrestamo) {
        this.fechaPrestamo = fechaPrestamo;
    }
    public String getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(String fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }




}


