//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFC_Service_Bec.WS_Actualizar_Bec {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="WS_Actualizar_Bec.Actualizar")]
    public interface Actualizar {
        
        // CODEGEN: Generating message contract since element name arg1 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/actualizarUsuarioRequest", ReplyAction="http://ws/Actualizar/actualizarUsuarioResponse")]
        WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioResponse actualizarUsuario(WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/actualizarUsuarioRequest", ReplyAction="http://ws/Actualizar/actualizarUsuarioResponse")]
        System.Threading.Tasks.Task<WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioResponse> actualizarUsuarioAsync(WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/actualizarRolRequest", ReplyAction="http://ws/Actualizar/actualizarRolResponse")]
        WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolResponse actualizarRol(WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/actualizarRolRequest", ReplyAction="http://ws/Actualizar/actualizarRolResponse")]
        System.Threading.Tasks.Task<WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolResponse> actualizarRolAsync(WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolRequest request);
        
        // CODEGEN: Generating message contract since element name arg1 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/ActualizarFichaRequest", ReplyAction="http://ws/Actualizar/ActualizarFichaResponse")]
        WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaResponse ActualizarFicha(WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Actualizar/ActualizarFichaRequest", ReplyAction="http://ws/Actualizar/ActualizarFichaResponse")]
        System.Threading.Tasks.Task<WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaResponse> ActualizarFichaAsync(WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarUsuario", Namespace="http://ws/", Order=0)]
        public WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioRequestBody Body;
        
        public actualizarUsuarioRequest() {
        }
        
        public actualizarUsuarioRequest(WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        public actualizarUsuarioRequestBody() {
        }
        
        public actualizarUsuarioRequestBody(int arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarUsuarioResponse", Namespace="http://ws/", Order=0)]
        public WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioResponseBody Body;
        
        public actualizarUsuarioResponse() {
        }
        
        public actualizarUsuarioResponse(WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public actualizarUsuarioResponseBody() {
        }
        
        public actualizarUsuarioResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarRolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarRol", Namespace="http://ws/", Order=0)]
        public WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolRequestBody Body;
        
        public actualizarRolRequest() {
        }
        
        public actualizarRolRequest(WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarRolRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public actualizarRolRequestBody() {
        }
        
        public actualizarRolRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarRolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarRolResponse", Namespace="http://ws/", Order=0)]
        public WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolResponseBody Body;
        
        public actualizarRolResponse() {
        }
        
        public actualizarRolResponse(WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarRolResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public actualizarRolResponseBody() {
        }
        
        public actualizarRolResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarFichaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarFicha", Namespace="http://ws/", Order=0)]
        public WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaRequestBody Body;
        
        public ActualizarFichaRequest() {
        }
        
        public ActualizarFichaRequest(WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ActualizarFichaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string arg5;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int arg6;
        
        public ActualizarFichaRequestBody() {
        }
        
        public ActualizarFichaRequestBody(int arg0, string arg1, string arg2, string arg3, string arg4, string arg5, int arg6) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarFichaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarFichaResponse", Namespace="http://ws/", Order=0)]
        public WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaResponseBody Body;
        
        public ActualizarFichaResponse() {
        }
        
        public ActualizarFichaResponse(WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ActualizarFichaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public ActualizarFichaResponseBody() {
        }
        
        public ActualizarFichaResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ActualizarChannel : WFC_Service_Bec.WS_Actualizar_Bec.Actualizar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActualizarClient : System.ServiceModel.ClientBase<WFC_Service_Bec.WS_Actualizar_Bec.Actualizar>, WFC_Service_Bec.WS_Actualizar_Bec.Actualizar {
        
        public ActualizarClient() {
        }
        
        public ActualizarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActualizarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActualizarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActualizarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioResponse WFC_Service_Bec.WS_Actualizar_Bec.Actualizar.actualizarUsuario(WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioRequest request) {
            return base.Channel.actualizarUsuario(request);
        }
        
        public bool actualizarUsuario(int arg0, string arg1, string arg2) {
            WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioRequest inValue = new WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioRequest();
            inValue.Body = new WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioResponse retVal = ((WFC_Service_Bec.WS_Actualizar_Bec.Actualizar)(this)).actualizarUsuario(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioResponse> WFC_Service_Bec.WS_Actualizar_Bec.Actualizar.actualizarUsuarioAsync(WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioRequest request) {
            return base.Channel.actualizarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioResponse> actualizarUsuarioAsync(int arg0, string arg1, string arg2) {
            WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioRequest inValue = new WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioRequest();
            inValue.Body = new WFC_Service_Bec.WS_Actualizar_Bec.actualizarUsuarioRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            return ((WFC_Service_Bec.WS_Actualizar_Bec.Actualizar)(this)).actualizarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolResponse WFC_Service_Bec.WS_Actualizar_Bec.Actualizar.actualizarRol(WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolRequest request) {
            return base.Channel.actualizarRol(request);
        }
        
        public bool actualizarRol(string arg0) {
            WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolRequest inValue = new WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolRequest();
            inValue.Body = new WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolRequestBody();
            inValue.Body.arg0 = arg0;
            WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolResponse retVal = ((WFC_Service_Bec.WS_Actualizar_Bec.Actualizar)(this)).actualizarRol(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolResponse> WFC_Service_Bec.WS_Actualizar_Bec.Actualizar.actualizarRolAsync(WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolRequest request) {
            return base.Channel.actualizarRolAsync(request);
        }
        
        public System.Threading.Tasks.Task<WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolResponse> actualizarRolAsync(string arg0) {
            WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolRequest inValue = new WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolRequest();
            inValue.Body = new WFC_Service_Bec.WS_Actualizar_Bec.actualizarRolRequestBody();
            inValue.Body.arg0 = arg0;
            return ((WFC_Service_Bec.WS_Actualizar_Bec.Actualizar)(this)).actualizarRolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaResponse WFC_Service_Bec.WS_Actualizar_Bec.Actualizar.ActualizarFicha(WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaRequest request) {
            return base.Channel.ActualizarFicha(request);
        }
        
        public bool ActualizarFicha(int arg0, string arg1, string arg2, string arg3, string arg4, string arg5, int arg6) {
            WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaRequest inValue = new WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaRequest();
            inValue.Body = new WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaResponse retVal = ((WFC_Service_Bec.WS_Actualizar_Bec.Actualizar)(this)).ActualizarFicha(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaResponse> WFC_Service_Bec.WS_Actualizar_Bec.Actualizar.ActualizarFichaAsync(WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaRequest request) {
            return base.Channel.ActualizarFichaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaResponse> ActualizarFichaAsync(int arg0, string arg1, string arg2, string arg3, string arg4, string arg5, int arg6) {
            WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaRequest inValue = new WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaRequest();
            inValue.Body = new WFC_Service_Bec.WS_Actualizar_Bec.ActualizarFichaRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            return ((WFC_Service_Bec.WS_Actualizar_Bec.Actualizar)(this)).ActualizarFichaAsync(inValue);
        }
    }
}
