//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="ServiceReference2.Agregar")]
    public interface Agregar {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarUsuario3Request", ReplyAction="http://ws/Agregar/insertarUsuario3Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WcfService1.ServiceReference2.insertarUsuario3Response insertarUsuario3(WcfService1.ServiceReference2.insertarUsuario3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarUsuario3Request", ReplyAction="http://ws/Agregar/insertarUsuario3Response")]
        System.Threading.Tasks.Task<WcfService1.ServiceReference2.insertarUsuario3Response> insertarUsuario3Async(WcfService1.ServiceReference2.insertarUsuario3Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarFichaRequest", ReplyAction="http://ws/Agregar/insertarFichaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WcfService1.ServiceReference2.insertarFichaResponse insertarFicha(WcfService1.ServiceReference2.insertarFichaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarFichaRequest", ReplyAction="http://ws/Agregar/insertarFichaResponse")]
        System.Threading.Tasks.Task<WcfService1.ServiceReference2.insertarFichaResponse> insertarFichaAsync(WcfService1.ServiceReference2.insertarFichaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarUsuarioRequest", ReplyAction="http://ws/Agregar/insertarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WcfService1.ServiceReference2.insertarUsuarioResponse insertarUsuario(WcfService1.ServiceReference2.insertarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarUsuarioRequest", ReplyAction="http://ws/Agregar/insertarUsuarioResponse")]
        System.Threading.Tasks.Task<WcfService1.ServiceReference2.insertarUsuarioResponse> insertarUsuarioAsync(WcfService1.ServiceReference2.insertarUsuarioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertaPrestamoRequest", ReplyAction="http://ws/Agregar/insertaPrestamoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WcfService1.ServiceReference2.insertaPrestamoResponse insertaPrestamo(WcfService1.ServiceReference2.insertaPrestamoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertaPrestamoRequest", ReplyAction="http://ws/Agregar/insertaPrestamoResponse")]
        System.Threading.Tasks.Task<WcfService1.ServiceReference2.insertaPrestamoResponse> insertaPrestamoAsync(WcfService1.ServiceReference2.insertaPrestamoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarUsuario2Request", ReplyAction="http://ws/Agregar/insertarUsuario2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WcfService1.ServiceReference2.insertarUsuario2Response insertarUsuario2(WcfService1.ServiceReference2.insertarUsuario2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarUsuario2Request", ReplyAction="http://ws/Agregar/insertarUsuario2Response")]
        System.Threading.Tasks.Task<WcfService1.ServiceReference2.insertarUsuario2Response> insertarUsuario2Async(WcfService1.ServiceReference2.insertarUsuario2Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarRolRequest", ReplyAction="http://ws/Agregar/insertarRolResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WcfService1.ServiceReference2.insertarRolResponse insertarRol(WcfService1.ServiceReference2.insertarRolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Agregar/insertarRolRequest", ReplyAction="http://ws/Agregar/insertarRolResponse")]
        System.Threading.Tasks.Task<WcfService1.ServiceReference2.insertarRolResponse> insertarRolAsync(WcfService1.ServiceReference2.insertarRolRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarUsuario3", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class insertarUsuario3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        public insertarUsuario3Request() {
        }
        
        public insertarUsuario3Request(string arg0, string arg1, int arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarUsuario3Response", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class insertarUsuario3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public insertarUsuario3Response() {
        }
        
        public insertarUsuario3Response(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarFicha", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class insertarFichaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg5;
        
        public insertarFichaRequest() {
        }
        
        public insertarFichaRequest(string arg0, string arg1, string arg2, string arg3, string arg4, int arg5) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarFichaResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class insertarFichaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarFichaResponse() {
        }
        
        public insertarFichaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarUsuario", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class insertarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        public insertarUsuarioRequest() {
        }
        
        public insertarUsuarioRequest(string arg0, string arg1, int arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarUsuarioResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class insertarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public insertarUsuarioResponse() {
        }
        
        public insertarUsuarioResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class date : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class rol : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idRolField;
        
        private bool idRolFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idRol {
            get {
                return this.idRolField;
            }
            set {
                this.idRolField = value;
                this.RaisePropertyChanged("idRol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idRolSpecified {
            get {
                return this.idRolFieldSpecified;
            }
            set {
                this.idRolFieldSpecified = value;
                this.RaisePropertyChanged("idRolSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class ficha : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string correoField;
        
        private string direccionField;
        
        private byte[] fotografiaField;
        
        private int huellaField;
        
        private int idFichaField;
        
        private bool idFichaFieldSpecified;
        
        private string nombresField;
        
        private string rutField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] fotografia {
            get {
                return this.fotografiaField;
            }
            set {
                this.fotografiaField = value;
                this.RaisePropertyChanged("fotografia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int huella {
            get {
                return this.huellaField;
            }
            set {
                this.huellaField = value;
                this.RaisePropertyChanged("huella");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idFicha {
            get {
                return this.idFichaField;
            }
            set {
                this.idFichaField = value;
                this.RaisePropertyChanged("idFicha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idFichaSpecified {
            get {
                return this.idFichaFieldSpecified;
            }
            set {
                this.idFichaFieldSpecified = value;
                this.RaisePropertyChanged("idFichaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claveField;
        
        private ficha fichaField;
        
        private int idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string nombreUsuarioField;
        
        private rol rolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ficha ficha {
            get {
                return this.fichaField;
            }
            set {
                this.fichaField = value;
                this.RaisePropertyChanged("ficha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("nombreUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public rol rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertaPrestamo", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class insertaPrestamoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WcfService1.ServiceReference2.date arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WcfService1.ServiceReference2.date arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WcfService1.ServiceReference2.usuario arg4;
        
        public insertaPrestamoRequest() {
        }
        
        public insertaPrestamoRequest(string arg0, string arg1, WcfService1.ServiceReference2.date arg2, WcfService1.ServiceReference2.date arg3, WcfService1.ServiceReference2.usuario arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertaPrestamoResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class insertaPrestamoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public insertaPrestamoResponse() {
        }
        
        public insertaPrestamoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarUsuario2", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class insertarUsuario2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        public insertarUsuario2Request() {
        }
        
        public insertarUsuario2Request(string arg0, string arg1, int arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarUsuario2Response", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class insertarUsuario2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public insertarUsuario2Response() {
        }
        
        public insertarUsuario2Response(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarRol", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class insertarRolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public insertarRolRequest() {
        }
        
        public insertarRolRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarRolResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class insertarRolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public insertarRolResponse() {
        }
        
        public insertarRolResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgregarChannel : WcfService1.ServiceReference2.Agregar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgregarClient : System.ServiceModel.ClientBase<WcfService1.ServiceReference2.Agregar>, WcfService1.ServiceReference2.Agregar {
        
        public AgregarClient() {
        }
        
        public AgregarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgregarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgregarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgregarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference2.insertarUsuario3Response WcfService1.ServiceReference2.Agregar.insertarUsuario3(WcfService1.ServiceReference2.insertarUsuario3Request request) {
            return base.Channel.insertarUsuario3(request);
        }
        
        public bool insertarUsuario3(string arg0, string arg1, int arg2) {
            WcfService1.ServiceReference2.insertarUsuario3Request inValue = new WcfService1.ServiceReference2.insertarUsuario3Request();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            WcfService1.ServiceReference2.insertarUsuario3Response retVal = ((WcfService1.ServiceReference2.Agregar)(this)).insertarUsuario3(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WcfService1.ServiceReference2.insertarUsuario3Response> WcfService1.ServiceReference2.Agregar.insertarUsuario3Async(WcfService1.ServiceReference2.insertarUsuario3Request request) {
            return base.Channel.insertarUsuario3Async(request);
        }
        
        public System.Threading.Tasks.Task<WcfService1.ServiceReference2.insertarUsuario3Response> insertarUsuario3Async(string arg0, string arg1, int arg2) {
            WcfService1.ServiceReference2.insertarUsuario3Request inValue = new WcfService1.ServiceReference2.insertarUsuario3Request();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((WcfService1.ServiceReference2.Agregar)(this)).insertarUsuario3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference2.insertarFichaResponse WcfService1.ServiceReference2.Agregar.insertarFicha(WcfService1.ServiceReference2.insertarFichaRequest request) {
            return base.Channel.insertarFicha(request);
        }
        
        public int insertarFicha(string arg0, string arg1, string arg2, string arg3, string arg4, int arg5) {
            WcfService1.ServiceReference2.insertarFichaRequest inValue = new WcfService1.ServiceReference2.insertarFichaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            WcfService1.ServiceReference2.insertarFichaResponse retVal = ((WcfService1.ServiceReference2.Agregar)(this)).insertarFicha(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WcfService1.ServiceReference2.insertarFichaResponse> WcfService1.ServiceReference2.Agregar.insertarFichaAsync(WcfService1.ServiceReference2.insertarFichaRequest request) {
            return base.Channel.insertarFichaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfService1.ServiceReference2.insertarFichaResponse> insertarFichaAsync(string arg0, string arg1, string arg2, string arg3, string arg4, int arg5) {
            WcfService1.ServiceReference2.insertarFichaRequest inValue = new WcfService1.ServiceReference2.insertarFichaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            return ((WcfService1.ServiceReference2.Agregar)(this)).insertarFichaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference2.insertarUsuarioResponse WcfService1.ServiceReference2.Agregar.insertarUsuario(WcfService1.ServiceReference2.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuario(request);
        }
        
        public bool insertarUsuario(string arg0, string arg1, int arg2) {
            WcfService1.ServiceReference2.insertarUsuarioRequest inValue = new WcfService1.ServiceReference2.insertarUsuarioRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            WcfService1.ServiceReference2.insertarUsuarioResponse retVal = ((WcfService1.ServiceReference2.Agregar)(this)).insertarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WcfService1.ServiceReference2.insertarUsuarioResponse> WcfService1.ServiceReference2.Agregar.insertarUsuarioAsync(WcfService1.ServiceReference2.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfService1.ServiceReference2.insertarUsuarioResponse> insertarUsuarioAsync(string arg0, string arg1, int arg2) {
            WcfService1.ServiceReference2.insertarUsuarioRequest inValue = new WcfService1.ServiceReference2.insertarUsuarioRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((WcfService1.ServiceReference2.Agregar)(this)).insertarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference2.insertaPrestamoResponse WcfService1.ServiceReference2.Agregar.insertaPrestamo(WcfService1.ServiceReference2.insertaPrestamoRequest request) {
            return base.Channel.insertaPrestamo(request);
        }
        
        public bool insertaPrestamo(string arg0, string arg1, WcfService1.ServiceReference2.date arg2, WcfService1.ServiceReference2.date arg3, WcfService1.ServiceReference2.usuario arg4) {
            WcfService1.ServiceReference2.insertaPrestamoRequest inValue = new WcfService1.ServiceReference2.insertaPrestamoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            WcfService1.ServiceReference2.insertaPrestamoResponse retVal = ((WcfService1.ServiceReference2.Agregar)(this)).insertaPrestamo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WcfService1.ServiceReference2.insertaPrestamoResponse> WcfService1.ServiceReference2.Agregar.insertaPrestamoAsync(WcfService1.ServiceReference2.insertaPrestamoRequest request) {
            return base.Channel.insertaPrestamoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfService1.ServiceReference2.insertaPrestamoResponse> insertaPrestamoAsync(string arg0, string arg1, WcfService1.ServiceReference2.date arg2, WcfService1.ServiceReference2.date arg3, WcfService1.ServiceReference2.usuario arg4) {
            WcfService1.ServiceReference2.insertaPrestamoRequest inValue = new WcfService1.ServiceReference2.insertaPrestamoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            return ((WcfService1.ServiceReference2.Agregar)(this)).insertaPrestamoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference2.insertarUsuario2Response WcfService1.ServiceReference2.Agregar.insertarUsuario2(WcfService1.ServiceReference2.insertarUsuario2Request request) {
            return base.Channel.insertarUsuario2(request);
        }
        
        public bool insertarUsuario2(string arg0, string arg1, int arg2) {
            WcfService1.ServiceReference2.insertarUsuario2Request inValue = new WcfService1.ServiceReference2.insertarUsuario2Request();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            WcfService1.ServiceReference2.insertarUsuario2Response retVal = ((WcfService1.ServiceReference2.Agregar)(this)).insertarUsuario2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WcfService1.ServiceReference2.insertarUsuario2Response> WcfService1.ServiceReference2.Agregar.insertarUsuario2Async(WcfService1.ServiceReference2.insertarUsuario2Request request) {
            return base.Channel.insertarUsuario2Async(request);
        }
        
        public System.Threading.Tasks.Task<WcfService1.ServiceReference2.insertarUsuario2Response> insertarUsuario2Async(string arg0, string arg1, int arg2) {
            WcfService1.ServiceReference2.insertarUsuario2Request inValue = new WcfService1.ServiceReference2.insertarUsuario2Request();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((WcfService1.ServiceReference2.Agregar)(this)).insertarUsuario2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference2.insertarRolResponse WcfService1.ServiceReference2.Agregar.insertarRol(WcfService1.ServiceReference2.insertarRolRequest request) {
            return base.Channel.insertarRol(request);
        }
        
        public bool insertarRol(string arg0) {
            WcfService1.ServiceReference2.insertarRolRequest inValue = new WcfService1.ServiceReference2.insertarRolRequest();
            inValue.arg0 = arg0;
            WcfService1.ServiceReference2.insertarRolResponse retVal = ((WcfService1.ServiceReference2.Agregar)(this)).insertarRol(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WcfService1.ServiceReference2.insertarRolResponse> WcfService1.ServiceReference2.Agregar.insertarRolAsync(WcfService1.ServiceReference2.insertarRolRequest request) {
            return base.Channel.insertarRolAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfService1.ServiceReference2.insertarRolResponse> insertarRolAsync(string arg0) {
            WcfService1.ServiceReference2.insertarRolRequest inValue = new WcfService1.ServiceReference2.insertarRolRequest();
            inValue.arg0 = arg0;
            return ((WcfService1.ServiceReference2.Agregar)(this)).insertarRolAsync(inValue);
        }
    }
}
