//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEC.WS_Login_Bec {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="WS_Login_Bec.Login")]
    public interface Login {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Login/LogearRequest", ReplyAction="http://ws/Login/LogearResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BEC.WS_Login_Bec.LogearResponse Logear(BEC.WS_Login_Bec.LogearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Login/LogearRequest", ReplyAction="http://ws/Login/LogearResponse")]
        System.Threading.Tasks.Task<BEC.WS_Login_Bec.LogearResponse> LogearAsync(BEC.WS_Login_Bec.LogearRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Login/ValidarIntRequest", ReplyAction="http://ws/Login/ValidarIntResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BEC.WS_Login_Bec.ValidarIntResponse ValidarInt(BEC.WS_Login_Bec.ValidarIntRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Login/ValidarIntRequest", ReplyAction="http://ws/Login/ValidarIntResponse")]
        System.Threading.Tasks.Task<BEC.WS_Login_Bec.ValidarIntResponse> ValidarIntAsync(BEC.WS_Login_Bec.ValidarIntRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Login/ValidarRequest", ReplyAction="http://ws/Login/ValidarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BEC.WS_Login_Bec.Exception), Action="http://ws/Login/Validar/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BEC.WS_Login_Bec.ValidarResponse Validar(BEC.WS_Login_Bec.ValidarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Login/ValidarRequest", ReplyAction="http://ws/Login/ValidarResponse")]
        System.Threading.Tasks.Task<BEC.WS_Login_Bec.ValidarResponse> ValidarAsync(BEC.WS_Login_Bec.ValidarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Login/iniciarSesionRequest", ReplyAction="http://ws/Login/iniciarSesionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BEC.WS_Login_Bec.iniciarSesionResponse iniciarSesion(BEC.WS_Login_Bec.iniciarSesionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Login/iniciarSesionRequest", ReplyAction="http://ws/Login/iniciarSesionResponse")]
        System.Threading.Tasks.Task<BEC.WS_Login_Bec.iniciarSesionResponse> iniciarSesionAsync(BEC.WS_Login_Bec.iniciarSesionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Logear", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class LogearRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public LogearRequest() {
        }
        
        public LogearRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogearResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class LogearResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public LogearResponse() {
        }
        
        public LogearResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarInt", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ValidarIntRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public ValidarIntRequest() {
        }
        
        public ValidarIntRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarIntResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ValidarIntResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public ValidarIntResponse() {
        }
        
        public ValidarIntResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Validar", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ValidarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public ValidarRequest() {
        }
        
        public ValidarRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ValidarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public ValidarResponse() {
        }
        
        public ValidarResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iniciarSesion", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class iniciarSesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public iniciarSesionRequest() {
        }
        
        public iniciarSesionRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iniciarSesionResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class iniciarSesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public iniciarSesionResponse() {
        }
        
        public iniciarSesionResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginChannel : BEC.WS_Login_Bec.Login, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginClient : System.ServiceModel.ClientBase<BEC.WS_Login_Bec.Login>, BEC.WS_Login_Bec.Login {
        
        public LoginClient() {
        }
        
        public LoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Login_Bec.LogearResponse BEC.WS_Login_Bec.Login.Logear(BEC.WS_Login_Bec.LogearRequest request) {
            return base.Channel.Logear(request);
        }
        
        public bool Logear(string arg0, string arg1) {
            BEC.WS_Login_Bec.LogearRequest inValue = new BEC.WS_Login_Bec.LogearRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            BEC.WS_Login_Bec.LogearResponse retVal = ((BEC.WS_Login_Bec.Login)(this)).Logear(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Login_Bec.LogearResponse> BEC.WS_Login_Bec.Login.LogearAsync(BEC.WS_Login_Bec.LogearRequest request) {
            return base.Channel.LogearAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Login_Bec.LogearResponse> LogearAsync(string arg0, string arg1) {
            BEC.WS_Login_Bec.LogearRequest inValue = new BEC.WS_Login_Bec.LogearRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((BEC.WS_Login_Bec.Login)(this)).LogearAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Login_Bec.ValidarIntResponse BEC.WS_Login_Bec.Login.ValidarInt(BEC.WS_Login_Bec.ValidarIntRequest request) {
            return base.Channel.ValidarInt(request);
        }
        
        public int ValidarInt(string arg0, string arg1) {
            BEC.WS_Login_Bec.ValidarIntRequest inValue = new BEC.WS_Login_Bec.ValidarIntRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            BEC.WS_Login_Bec.ValidarIntResponse retVal = ((BEC.WS_Login_Bec.Login)(this)).ValidarInt(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Login_Bec.ValidarIntResponse> BEC.WS_Login_Bec.Login.ValidarIntAsync(BEC.WS_Login_Bec.ValidarIntRequest request) {
            return base.Channel.ValidarIntAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Login_Bec.ValidarIntResponse> ValidarIntAsync(string arg0, string arg1) {
            BEC.WS_Login_Bec.ValidarIntRequest inValue = new BEC.WS_Login_Bec.ValidarIntRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((BEC.WS_Login_Bec.Login)(this)).ValidarIntAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Login_Bec.ValidarResponse BEC.WS_Login_Bec.Login.Validar(BEC.WS_Login_Bec.ValidarRequest request) {
            return base.Channel.Validar(request);
        }
        
        public bool Validar(string arg0, string arg1) {
            BEC.WS_Login_Bec.ValidarRequest inValue = new BEC.WS_Login_Bec.ValidarRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            BEC.WS_Login_Bec.ValidarResponse retVal = ((BEC.WS_Login_Bec.Login)(this)).Validar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Login_Bec.ValidarResponse> BEC.WS_Login_Bec.Login.ValidarAsync(BEC.WS_Login_Bec.ValidarRequest request) {
            return base.Channel.ValidarAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Login_Bec.ValidarResponse> ValidarAsync(string arg0, string arg1) {
            BEC.WS_Login_Bec.ValidarRequest inValue = new BEC.WS_Login_Bec.ValidarRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((BEC.WS_Login_Bec.Login)(this)).ValidarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEC.WS_Login_Bec.iniciarSesionResponse BEC.WS_Login_Bec.Login.iniciarSesion(BEC.WS_Login_Bec.iniciarSesionRequest request) {
            return base.Channel.iniciarSesion(request);
        }
        
        public bool iniciarSesion(int arg0) {
            BEC.WS_Login_Bec.iniciarSesionRequest inValue = new BEC.WS_Login_Bec.iniciarSesionRequest();
            inValue.arg0 = arg0;
            BEC.WS_Login_Bec.iniciarSesionResponse retVal = ((BEC.WS_Login_Bec.Login)(this)).iniciarSesion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BEC.WS_Login_Bec.iniciarSesionResponse> BEC.WS_Login_Bec.Login.iniciarSesionAsync(BEC.WS_Login_Bec.iniciarSesionRequest request) {
            return base.Channel.iniciarSesionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BEC.WS_Login_Bec.iniciarSesionResponse> iniciarSesionAsync(int arg0) {
            BEC.WS_Login_Bec.iniciarSesionRequest inValue = new BEC.WS_Login_Bec.iniciarSesionRequest();
            inValue.arg0 = arg0;
            return ((BEC.WS_Login_Bec.Login)(this)).iniciarSesionAsync(inValue);
        }
    }
}
