//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFC_Service_Bec.WS_Eliminar_Bec {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="WS_Eliminar_Bec.Eliminar")]
    public interface Eliminar {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://ws/)
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Eliminar/eliminarFichaRequest", ReplyAction="http://ws/Eliminar/eliminarFichaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WFC_Service_Bec.WS_Eliminar_Bec.eliminarFichaResponse eliminarFicha(WFC_Service_Bec.WS_Eliminar_Bec.eliminarFichaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Eliminar/eliminarFichaRequest", ReplyAction="http://ws/Eliminar/eliminarFichaResponse")]
        System.Threading.Tasks.Task<WFC_Service_Bec.WS_Eliminar_Bec.eliminarFichaResponse> eliminarFichaAsync(WFC_Service_Bec.WS_Eliminar_Bec.eliminarFichaRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://ws/)
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Eliminar/eliminarRolRequest", ReplyAction="http://ws/Eliminar/eliminarRolResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WFC_Service_Bec.WS_Eliminar_Bec.eliminarRolResponse eliminarRol(WFC_Service_Bec.WS_Eliminar_Bec.eliminarRolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Eliminar/eliminarRolRequest", ReplyAction="http://ws/Eliminar/eliminarRolResponse")]
        System.Threading.Tasks.Task<WFC_Service_Bec.WS_Eliminar_Bec.eliminarRolResponse> eliminarRolAsync(WFC_Service_Bec.WS_Eliminar_Bec.eliminarRolRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://ws/)
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Eliminar/eliminarUsuarioRequest", ReplyAction="http://ws/Eliminar/eliminarUsuarioResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WFC_Service_Bec.WS_Eliminar_Bec.eliminarUsuarioResponse eliminarUsuario(WFC_Service_Bec.WS_Eliminar_Bec.eliminarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/Eliminar/eliminarUsuarioRequest", ReplyAction="http://ws/Eliminar/eliminarUsuarioResponse")]
        System.Threading.Tasks.Task<WFC_Service_Bec.WS_Eliminar_Bec.eliminarUsuarioResponse> eliminarUsuarioAsync(WFC_Service_Bec.WS_Eliminar_Bec.eliminarUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarFicha", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class eliminarFichaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        public eliminarFichaRequest() {
        }
        
        public eliminarFichaRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarFichaResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class eliminarFichaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public eliminarFichaResponse() {
        }
        
        public eliminarFichaResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarRol", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class eliminarRolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        public eliminarRolRequest() {
        }
        
        public eliminarRolRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarRolResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class eliminarRolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public eliminarRolResponse() {
        }
        
        public eliminarRolResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarUsuario", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class eliminarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        public eliminarUsuarioRequest() {
        }
        
        public eliminarUsuarioRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarUsuarioResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class eliminarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public eliminarUsuarioResponse() {
        }
        
        public eliminarUsuarioResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EliminarChannel : WFC_Service_Bec.WS_Eliminar_Bec.Eliminar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EliminarClient : System.ServiceModel.ClientBase<WFC_Service_Bec.WS_Eliminar_Bec.Eliminar>, WFC_Service_Bec.WS_Eliminar_Bec.Eliminar {
        
        public EliminarClient() {
        }
        
        public EliminarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EliminarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EliminarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EliminarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WFC_Service_Bec.WS_Eliminar_Bec.eliminarFichaResponse WFC_Service_Bec.WS_Eliminar_Bec.Eliminar.eliminarFicha(WFC_Service_Bec.WS_Eliminar_Bec.eliminarFichaRequest request) {
            return base.Channel.eliminarFicha(request);
        }
        
        public bool eliminarFicha(int arg0) {
            WFC_Service_Bec.WS_Eliminar_Bec.eliminarFichaRequest inValue = new WFC_Service_Bec.WS_Eliminar_Bec.eliminarFichaRequest();
            inValue.arg0 = arg0;
            WFC_Service_Bec.WS_Eliminar_Bec.eliminarFichaResponse retVal = ((WFC_Service_Bec.WS_Eliminar_Bec.Eliminar)(this)).eliminarFicha(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WFC_Service_Bec.WS_Eliminar_Bec.eliminarFichaResponse> WFC_Service_Bec.WS_Eliminar_Bec.Eliminar.eliminarFichaAsync(WFC_Service_Bec.WS_Eliminar_Bec.eliminarFichaRequest request) {
            return base.Channel.eliminarFichaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WFC_Service_Bec.WS_Eliminar_Bec.eliminarFichaResponse> eliminarFichaAsync(int arg0) {
            WFC_Service_Bec.WS_Eliminar_Bec.eliminarFichaRequest inValue = new WFC_Service_Bec.WS_Eliminar_Bec.eliminarFichaRequest();
            inValue.arg0 = arg0;
            return ((WFC_Service_Bec.WS_Eliminar_Bec.Eliminar)(this)).eliminarFichaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WFC_Service_Bec.WS_Eliminar_Bec.eliminarRolResponse WFC_Service_Bec.WS_Eliminar_Bec.Eliminar.eliminarRol(WFC_Service_Bec.WS_Eliminar_Bec.eliminarRolRequest request) {
            return base.Channel.eliminarRol(request);
        }
        
        public bool eliminarRol(int arg0) {
            WFC_Service_Bec.WS_Eliminar_Bec.eliminarRolRequest inValue = new WFC_Service_Bec.WS_Eliminar_Bec.eliminarRolRequest();
            inValue.arg0 = arg0;
            WFC_Service_Bec.WS_Eliminar_Bec.eliminarRolResponse retVal = ((WFC_Service_Bec.WS_Eliminar_Bec.Eliminar)(this)).eliminarRol(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WFC_Service_Bec.WS_Eliminar_Bec.eliminarRolResponse> WFC_Service_Bec.WS_Eliminar_Bec.Eliminar.eliminarRolAsync(WFC_Service_Bec.WS_Eliminar_Bec.eliminarRolRequest request) {
            return base.Channel.eliminarRolAsync(request);
        }
        
        public System.Threading.Tasks.Task<WFC_Service_Bec.WS_Eliminar_Bec.eliminarRolResponse> eliminarRolAsync(int arg0) {
            WFC_Service_Bec.WS_Eliminar_Bec.eliminarRolRequest inValue = new WFC_Service_Bec.WS_Eliminar_Bec.eliminarRolRequest();
            inValue.arg0 = arg0;
            return ((WFC_Service_Bec.WS_Eliminar_Bec.Eliminar)(this)).eliminarRolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WFC_Service_Bec.WS_Eliminar_Bec.eliminarUsuarioResponse WFC_Service_Bec.WS_Eliminar_Bec.Eliminar.eliminarUsuario(WFC_Service_Bec.WS_Eliminar_Bec.eliminarUsuarioRequest request) {
            return base.Channel.eliminarUsuario(request);
        }
        
        public bool eliminarUsuario(int arg0) {
            WFC_Service_Bec.WS_Eliminar_Bec.eliminarUsuarioRequest inValue = new WFC_Service_Bec.WS_Eliminar_Bec.eliminarUsuarioRequest();
            inValue.arg0 = arg0;
            WFC_Service_Bec.WS_Eliminar_Bec.eliminarUsuarioResponse retVal = ((WFC_Service_Bec.WS_Eliminar_Bec.Eliminar)(this)).eliminarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WFC_Service_Bec.WS_Eliminar_Bec.eliminarUsuarioResponse> WFC_Service_Bec.WS_Eliminar_Bec.Eliminar.eliminarUsuarioAsync(WFC_Service_Bec.WS_Eliminar_Bec.eliminarUsuarioRequest request) {
            return base.Channel.eliminarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WFC_Service_Bec.WS_Eliminar_Bec.eliminarUsuarioResponse> eliminarUsuarioAsync(int arg0) {
            WFC_Service_Bec.WS_Eliminar_Bec.eliminarUsuarioRequest inValue = new WFC_Service_Bec.WS_Eliminar_Bec.eliminarUsuarioRequest();
            inValue.arg0 = arg0;
            return ((WFC_Service_Bec.WS_Eliminar_Bec.Eliminar)(this)).eliminarUsuarioAsync(inValue);
        }
    }
}
